config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :docs
  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end
  
  root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
    @docs = Doc.where(user_id: current_user)
  end

  def show
  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)

    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private
    def find_doc
      @doc = Doc.find(params[:id]) 
    end

    def doc_params
      params.require(:doc).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.haml
= simple_form_for @doc do |f|
  =f.input :title 
  =f.input :content
  =f.button :submit

app/views/docs/edit.haml
%h1 Fix %Doc

= render 'form'

=link_to "Cancel", doc_path

app/views/docs/index.haml
-@docs.each do |d|
  %h2= link_to d.title, d 
  %p= time_ago_in_words(d.created_at)
  %p= truncate(d.content, length:50)

=link_to "Buat Doc", new_doc_path

app/views/docs/new.haml
%h1 new Doc!

= render 'form'

app/views/docs/show.haml
%h1= @doc.title
%p= @doc.content

= link_to "All Docs", docs_path
= link_to "Fix Doc", edit_doc_path(@doc)
= link_to "Trash It", doc_path(@doc), method: :delete, data: {confirm: "Lo yakin?"}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cabinet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.haml
%h1 Wei Bro! ini placeholdernya